<script lang="ts">
	import { faqs } from '$lib/data/faq';
	import type { PerformQueryResponse } from '$lib/utils/google-gen-ai/embedding';
	import { Accordion, AccordionItem } from '@skeletonlabs/skeleton';
	import SvelteMarkdown from 'svelte-markdown';

	let query = '';
	let results: PerformQueryResponse[] = [];
	let loading = false;

	const onTextKeyDown = (e: KeyboardEvent) => {
		if (e.key === 'Enter' && !e.shiftKey) {
			e.stopPropagation();
			e.preventDefault();
			search();
		}
	};

	const search = async () => {
		try {
			loading = true;

			const response = await fetch('/api/faq', {
				method: 'POST',
				body: JSON.stringify({
					query
				})
			});

			if (response.ok) {
				const responseBody = await response.json();
				results = responseBody;
			}
		} catch (error) {
			alert('Erro');
		} finally {
			loading = false;
		}
	};

	const cleanSearch = () => {
		results = [];
		query = '';
	};
</script>

<section class="container mx-auto space-y-8 p-8">
	<h1 class="h1">Questions and Answers About Yoga 🧘‍♂️</h1>
	<p>I hope these questions and answers have helped you better understand Yoga. Namaste! 🙏</p>

	<aside class="alert variant-ghost-secondary">
		<p>
			These questions and answers were generated by <strong>Google Gemini</strong> through
			<strong>Google AI Studio</strong>.
			<br />
			<strong>Prompt used:</strong>
			<i>"Generate 20 questions and answers related to Yoga. Use emojis."</i>
			<br />
			<br />
			These questions and answers are used in the application of the <strong>Embedding</strong>
			concept to return predefined answers based on the context of the question in the chat.
		</p>
	</aside>

	<div class="card variant-ringed p-8">
		<h3 class="h3 mb-4 text-center">Search in our frequently asked questions</h3>
		<div class="input-group input-group-divider grid-cols-[1fr_auto_auto] rounded-container-token">
			<textarea
				bind:value={query}
				class="border-0 bg-transparent p-2 ring-0"
				name="prompt"
				id="prompt"
				placeholder="Type a search query and click 'Search' or press Enter..."
				rows="1"
				on:keydown={onTextKeyDown}
				disabled={loading}
			/>
			<button class="variant-soft" on:click={cleanSearch} disabled={loading}>Clear</button>
			<button class="variant-filled-primary" on:click={search} disabled={loading}>Search</button>
		</div>
	</div>

	{#if results && results.length}
		<h4 class="h4">Here are the 3 most relevant results for your search.:</h4>
	{/if}

	{#if loading}
		<div class="placeholder animate-pulse" />
		<div class="placeholder animate-pulse" />
		<div class="placeholder animate-pulse" />
	{:else}
		<Accordion autocollapse spacing="space-y-4">
			{#if results && results.length}
				{#each results as result, index}
					<AccordionItem class="variant-soft " open={index === 0}>
						<svelte:fragment slot="summary">
							<strong>{result.faq.question}</strong>
							<span class="ml-4">
								(Score: {result.percentage.toLocaleString()}%)
							</span>
						</svelte:fragment>
						<svelte:fragment slot="content">
							<div class="markdown">
								<SvelteMarkdown source={result.faq.answer} />
							</div>
						</svelte:fragment>
					</AccordionItem>
				{/each}
			{:else}
				{#each faqs as faq, index}
					<AccordionItem class="variant-soft " open={index === 0}>
						<svelte:fragment slot="summary"><strong>{faq.question} </strong></svelte:fragment>
						<svelte:fragment slot="content">
							<div class="markdown">
								<SvelteMarkdown source={faq.answer} />
							</div>
						</svelte:fragment>
					</AccordionItem>
				{/each}
			{/if}
		</Accordion>
	{/if}
</section>
